# Stdr Simulator Travis Continuous Integration Configuration File
# Author: Christos Zalidis
sudo: required
dist: trusty
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - etsardou@gmail.com
      - zalidis@gmail.com
      - aris.thallas@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export ROS_DISTRO=indigo
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - mkdir -p ~/ros/ws_stdr/src
  - cd ~/ros/ws_stdr/src
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - cd ../
  # Install dependencies for source repos
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - catkin_make -j2
  - source devel/setup.bash
  - catkin_make run_tests -j1
  - catkin_test_results build
